services:
  - type: web
    name: geekquiz
    env: docker
    plan: starter
    buildCommand: echo "Build completed"
    startCommand: apache2-foreground
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geekquiz-db
          property: connectionString

databases:
  - name: geekquiz-db
    plan: starter